### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by abinrm** [degordian/swift-jab#5]
Hi, is there any way that in the future there will be support for carthage?

Thanks!

**Comment by d-srd** [comment]
Sure! 

Our priority is currently bug fixing, but adding support for Carthage shouldn't take much effort. You can expect this to be done by the end of the week.

**Comment by d-srd** [comment]
Should be good to go. If you have any problems, feel free to reopen the issue.

**Comment by abinrm** [comment]
I tried to add through Carthage, I get the following error 
<img width="570" alt="Screenshot 2019-10-07 at 3 15 37 PM" src="https://user-images.githubusercontent.com/36157771/66315099-66cff300-e915-11e9-95d0-c52200fa18f4.png">

Maybe the schemes are in a location which is ignored by `.gitignore` file? 
Reference [link](https://www.amerhukic.com/how-to-add-carthage-support-in-existing-cocoapod-project)

**Comment by d-srd** [comment]
Yep, it was gitignored. Fixed :)
